# serverless.yml
service: my-service
provider:
  name: aws
  runtime: nodejs6.10
functions:
  hello:
    handler: functions/handler.hello
    events:
      - http:
          path: hello/get
          method: get
  user:
    handler: functions/user.getuser
    events:
      - http:
          path: user
          method: get

# adding these two lines
plugins:
  - serverless-offline
