# serverless.yml
service: my-service
provider:
  name: aws
  runtime: nodejs6.10
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello/get
          method: get
  test:
    handler: handler.test
    events:
      - http:
          path: test/get
          method: get

# adding these two lines
plugins:
  - serverless-offline
